---
openapi: 3.0.3
info:
  title: Trading Service API
  version: 1.0.0
tags:
- name: Trading
  description: Securities trading operations
paths:
  /api/v1/trades/buy:
    post:
      tags:
      - Trading
      summary: Execute buy order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TradeRequest'
      responses:
        "200":
          description: OK
  /api/v1/trades/sell:
    post:
      tags:
      - Trading
      summary: Execute sell order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TradeRequest'
      responses:
        "200":
          description: OK
components:
  schemas:
    Currency:
      enum:
      - USD
      - EUR
      - GBP
      type: string
    OrderType:
      enum:
      - BY_AMOUNT
      - BY_QUANTITY
      type: string
    TradeRequest:
      type: object
      properties:
        userId:
          $ref: '#/components/schemas/UUID'
        symbol:
          type: string
        currency:
          $ref: '#/components/schemas/Currency'
        orderType:
          $ref: '#/components/schemas/OrderType'
        amount:
          type: number
        quantity:
          type: number
    UUID:
      format: uuid
      pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
      type: string
